### PR TITLE
Informs users of possible incorrect port name

### PR DESCRIPTION
**Pull request by mgroth0**
This would have saved me a lot of time if it were written in here, so I think it would be helpful to others.

### CODE REVIEW

**Comment by biomurph** [comment]
Hi,
I'm not sure how this error you mention comes up. Are you using the Serial Port Selection tool in the GUI when it's running?

**Comment by mgroth0** [comment]
Hi,

I'm not sure what you mean. The "BLE Devices" list? This list was empty before I fixed the port name. I looked through the GUI and didn't see any "Serial Port Selection tool". In case you haven't seen, [I also made a pull request on OpenBCI GUI itself regarding the same issue](https://github.com/OpenBCI/OpenBCI_GUI/pull/122). This can hopefully help show where my issue came from.

**Comment by biomurph** [comment]
Oh, I see your pull request on the GUI.
We will review it there, and if we can merge it to fix, then we won't need to adjust these Docs

**Comment by mgroth0** [comment]
Ok, only my fix is only tested on Mac. Also now I'm unsure if this is the correct port given the [other issue I'm having with data visualization](https://github.com/OpenBCI/OpenBCI_GUI/issues/123). I didn't think these were related because my fix stopped me from getting the output:   
```
catch (RuntimeException e) {
    verbosePrint("OpenBCI_GUI.pde: could not open " + serial_output_portName);
  }
```

but @aj-ptw said that you mentioned this might be a different kind of port.

**Comment by andrewjaykeller** [comment]
@matthew-groth are you using a Ganglion or Cyton? I'd like to close this PR if you are using a Ganglion and solve the real issue! thanks for the PR

**Comment by mgroth0** [comment]
Yes, I am using the Ganglion. Thanks!

**Pull request closed without merging**
